# #:kivy

<Button>:
    font_size: 32
    color: 0.3, 0.6, 0.7, 1
    size_hint: 0.3, 0.5

<FloatLayout>:
    Button: 
        id: writeBtn
        # every value is 0-1, the 
        pos_hint: {"x": 0.5, "top": 1}
        text: "Write"

    Button:
        id: readBtn
        pos_hint: {"y": 0.3}
        text: "Read" if readBtn.state == "normal" else "You are currently in Read Mode"
        # font_size: 32 if readBtn == "normal" else 20
    
